### ISSUE TITLE
Greenshot does not always capture the selected image (clipboard is emptly) on Windows 10/64 bit

### ISSUE THREAD

**Issue by bmotoc** [greenshot/greenshot#172]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmotoc** [comment]
With powerpoint and word open, greenshot does not always copy the image to clipboard (windows 10/64 bit). If I repeat the capture, I end getting the copy after 3 -4 attempts, with the difference between fail and success being the delay in getting the audio confirmation (immediate audio confirmation marks success, delayed audio confirmation marks failure to copy).

**Comment by asvc** [comment]
Can't reproduce here. Have you tried the [latest "unstable" version](https://github.com/greenshot/greenshot/releases/tag/v1.3.69)?

**Comment by Lakritzator** [comment]
What you describe is that Greenshot somehow doesn't get access to the clipboard, it will retry a couple of times and this is causing the delay. The reason for this is still unclear, it's one of those silly "work for me" issues.

What I do know, that in general it has to do with other clipboard viewers being active.
I've been working on a clipboard tool, learning much about it, for this I wrote quite a lot of clipboard code which should be used in Greenshot 2.x.

Please do try one of the latest releases, as we upgraded from .NET 2.0/3.5 to a .NET 4.7.2 which might fix quite a lot of weird issues.

**Comment by bmotoc** [comment]
Thank you :) Windows is a jungle
B

**Comment by Lakritzator** [comment]
@bmotoc did you try one of our unstable versions?

**Comment by paulogeneses** [comment]
Hey, guys. 

I had that same problem with stable version.Tried the latest unstable version and my problem was solved!
:)

**Comment by MitchTalmadge** [comment]
This still happens for me; if the clipboard option takes a while, then even though it says it is copied to the clipboard, it will not actually be there. Sometimes it is instant and it works fine. I am on the latest unstable version 1.3.219, on Windows 11.

I also have Enpass installed which is the only other app I can think of which might monitor the clipboard.

**Comment by Lakritzator** [comment]
As we have reports of multiple clipboard issues, I had another look at it.
First I just want to point out: to our knowledge Greenshot sticks to the described documentation & standards when implementing the clipboard.

But as we found many information and misinformation on the topic, I thought why not give it a go an replace our current formats with something which seems to be more successful in other applications.

The most recent change was made yesterday, and I would love to know if this happens to solve your issue.
This change is in 1.3.235, which can be found here: https://github.com/greenshot/greenshot/releases

I do not know if this solves the problems, I do not have them myself. But there are reasons for me to try this, so if possible, please play around with it and report back.
