### ISSUE TITLE
Shortcuts don't get created

### ISSUE THREAD

**Issue by hudsonm62** [greenshot/greenshot#611]
**Describe the bug**
Shortcuts don't get created on New Installation of 1.3.290

**To Reproduce**
Example steps to reproduce the behavior:
1. Run installer
2. Enable shortcut creation (or run installer silently)
3. Check User and System start menu folders - Shortcut missing
4. Check Public and user Desktops - Shortcut missing

User: `%appdata%\Microsoft\Windows\Start Menu\Programs`
&
System: `%programdata%\Microsoft\Windows\Start Menu\Programs`

**Expected behavior**
Shortcut should be created in start menu or desktop, so Greenshot app becomes searchable

**Screenshots**

**Versions (please complete the following information):**
 - Greenshot 1.3.290
 - Windows 11

**Additional context**
 - Issue doesn't occur in older versions

**Comment by FF-Brown** [comment]
Seems to be Win11-related. I installed on Win10 and got the start menu shortcut.

**Comment by hudsonm62** [comment]
> Seems to be Win11-related. I installed on Win10 and got the start menu shortcut.

huh interesting, i didnt have a win10 vm handy to test with

at any rate [windows 10 goes end of life in october](https://support.microsoft.com/en-au/windows/windows-10-support-ends-on-october-14-2025-2ca8b313-1946-43d3-b55c-2b95b107f281) so still needs to be fixed

**Comment by FF-Brown** [comment]
Yikes didn't realize it was that soon lol

**Comment by jklingen** [comment]
Could you check again with the latest stable v1.3.292?

Should be fixed with https://github.com/greenshot/greenshot/issues/546 / https://github.com/greenshot/greenshot/issues/619 .

**Comment by JamesPratt-LWL** [comment]
Fixed, thank you - Now in C:\Program Files using /ALLUSERS.

**Comment by hudsonm62** [comment]
> Could you check again with the latest stable v1.3.292?
> 
> Should be fixed with [#546](https://github.com/greenshot/greenshot/issues/546) / [#619](https://github.com/greenshot/greenshot/issues/619) .

thank you sirrr

**Comment by MikaelKW** [comment]
When we try to deploy the new version via Intune with the following command (being run as SYSTEM) no shortcuts get's created for users, as well as not being searchable with the latest version:
Greenshot-INSTALLER-1.3.292-RELEASE.exe /VERYSILENT /NORESTART /SUPPRESSMSGBOXES

However reinstalling the old version and running the same command just adjusted for the old version, shortcuts are made and Greenshot is searchable:
Greenshot-INSTALLER-1.2.10.6-RELEASE.exe /VERYSILENT /NORESTART /SUPPRESSMSGBOXES

**Comment by kgranad3** [comment]
> When we try to deploy the new version via Intune with the following command (being run as SYSTEM) no shortcuts get's created for users, as well as not being searchable with the latest version: Greenshot-INSTALLER-1.3.292-RELEASE.exe /VERYSILENT /NORESTART /SUPPRESSMSGBOXES
> 
> However reinstalling the old version and running the same command just adjusted for the old version, shortcuts are made and Greenshot is searchable: Greenshot-INSTALLER-1.2.10.6-RELEASE.exe /VERYSILENT /NORESTART /SUPPRESSMSGBOXES

I'm experiencing the same thing trying to deploy new version 1.3.292 under SYSTEM. Version 1.2.10.6 works as expected but not 1.3.292.

**Comment by MikaelKW** [comment]
@hudsonm62 Hi. Do you think the issue me @KattieGranados are facing is related to this issue, or is this a seperate issue?

**Comment by MikaelKW** [comment]
@jklingen is this the same issue as what me and @KattieGranados is facing, or is this e seperate issue?

**Comment by ghost** [comment]
I have the same problem
<details><summary>Screenshot</summary>

<img width="788" height="665" alt="Image" src="https://github.com/user-attachments/assets/ce1408fb-27b7-4b35-bfaa-cdd06d4bd517" />

</details>

Greenshot version: 1.3.292
Win 10

**Comment by jklingen** [comment]
We'll check again.

**Comment by jklingen** [comment]
The registry entries have been fixed in the latest bugfix release 1.3.296. As far as I can see, this also fixes the start menu entries. Can you confirm?

Thanks a lot.

**Comment by MikaelKW** [comment]
> The registry entries have been fixed in the latest bugfix release 1.3.296. As far as I can see, this also fixes the start menu entries. Can you confirm?
> 
> Thanks a lot.

~~Greenshot still not showing up in start menu/tray when installing the new version as SYSTEM through Intune or with an RMM agent~~

**Comment by MikaelKW** [comment]
Correction. Shows up after a reboot.

Edit: Is it possible to avoid having to do a reboot for Greenshot to show up, like with version 1.2.10.6?

**Comment by kgranad3** [comment]
Deploying software as SYSTEM works now after 1.3.296! The only difference is that with previous versions, Greenshot would appear in the system tray immediately after install, and now you have to run it first to get it to pop up, but that may be intentional and it's not really an issue.

**Comment by MikaelKW** [comment]
My discoveries so far:
1. If we make a script that uninstalls the old version of Greenshot, then installs the new, the new version will not show up in control panel (for uninstalling software), in Windows Search, or in the tray until a reboot
2. If we deploy the new version with a pre-script that only kills the greenshot.exe process, Greenshot remains in Windows Search, and i can see the new version in control panel. However like Kattie said, it does not start automatically.

**Comment by jklingen** [comment]
@KattieGranados @MikaelKW I can't reproduce any of what you describe in the last two comments... how exactly are you running the installer?

**Comment by MikaelKW** [comment]
> @KattieGranados @MikaelKW I can't reproduce any of what you describe in the last two comments... how exactly are you running the installer?

Are you installing as SYSTEM (not administrator)? We use NinjaRMM or Intune to install/update it.

**Comment by jklingen** [comment]
> SYSTEM (not administrator)

Thanks for clarification. I'm not experienced with these deployment tools and I'm not sure why they need to install as SYSTEM (neither whether Innosetup is designed for that use case). Usually, admin level is sufficient for an all users installation.

That said, from the examples posted above, it seems that you're **not** using the `/ALLUSERS` flag right? This could explain the behavior. I think Greenshot 1.2 defaulted to all-users installation when run privileged. 🤔

**Comment by jklingen** [comment]
Please let me know whether `/ALLUSERS` works as expected for you, otherwise I assume this issue resolved. Thanks.

**Comment by MikaelKW** [comment]
> Please let me know whether `/ALLUSERS` works as expected for you, otherwise I assume this issue resolved. Thanks.

I'll try to test it today if i get the time

**Comment by MikaelKW** [comment]
Case closed.

Need to use the following parameters in 1.3: Greenshot-INSTALLER-1.3.296-RELEASE.exe /VERYSILENT /SUPPRESSMSGBOXES /ALLUSERS

**Comment by jklingen** [comment]
Thanks for reporting back 👍  I am glad to hear it's working now. Closing this.
